### ISSUE TITLE
你好我想要支持 latex公司不知道可以支持这个功能不？

### ISSUE THREAD

**Issue by zzhgithub** [nshen/coding-blog#3]

**Comment by nshen** [comment]
没用过latex，不太确定呀，但内部用的 `metalsmith-markdown` 将md文件转成html，你可以查看一下是否支持，所有build代码都在这里
https://github.com/nshen/coding-blog/blob/master/build.js

**Comment by zzhgithub** [comment]
谢谢回复 
我已经找到方法了

const mathjax = require('metalsmith-mathjax');
![image](https://user-images.githubusercontent.com/12131877/61600820-42913e00-ac65-11e9-8bbb-7aac1fe4cda5.png)

使用这个包 然后在每个post文件里 头部加上
mathjax: true
就可以写了

我懒的提交了 ：）
